### ISSUE TITLE
Migration from Cling

### ISSUE THREAD

**Issue by SubJunk** [jupnp/jupnp#137]
Hi, I'm looking into migrating https://github.com/UniversalMediaServer/UniversalMediaServer from Cling to JUPnP and I have a couple of related questions. Any help would be appreciated.

1) Is there any different syntax to Cling or is it just a case of swapping the packages?
2) One reason we are looking for a replacement for Cling is because we want to use newer Java versions, which isn't possible with that unmaintained project. I notice in your readme you don't support newer than Java 8, but that there have been some changes to support the newer versions like https://github.com/jupnp/jupnp/pull/112
Would you be open to receiving incoming PRs to further fix compatibility with newer JREs?

Thanks :)

**Comment by kaikreuzer** [comment]
Hi @SubJunk!
Let me try to answer your questions:
1. JUPnP has evolved over time and there might be some breaking changes here and there, especially as we made the code work well in OSGi environments. In general, most public classes and interfaces should be pretty similar to Cling, but you shouldn't expect a no-hassle drop in replacement.
2. We keep the code base on Java 8, so that it can (also) run on Java 8. This does not mean that JUPnP is incompatible with newer Java versions. At openHAB (the main adopter of JUPnP), we are on Java 11 and use JUPnP smoothly. I would expect it to work nicely on Java 14 and above as well. If you find issues, PRs are always welcome as long as they do not break the compatibility with older Java versions.

**Comment by SubJunk** [comment]
@kaikreuzer thanks for your reply, that sounds good to me. Will try it and let you know how it goes

**Comment by SubJunk** [comment]
We tried to do this migration and it was more difficult than anticipated so we ended up rolling back to Java 8 instead for now. We still want to do this long-term though.

**Comment by SubJunk** [comment]
@ijabz thanks for jaudiotagger :) very nice
You might find some clues in the PRs https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2806 and https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2843
