### ISSUE TITLE
Code should work with Java 8 Compact Profile 2

### ISSUE THREAD

**Issue by kaikreuzer** [jupnp/jupnp#25]
The jupnp code currently uses the java.beans package, which is not part of any compact profile. As it is only a small functionality, this dependency should be removed by implementing it in a different way.

**Comment by JochenHiller** [comment]
I did a first prototype to see what needs to be changed to rely on compact 2 profile only.
I had to change:
* Replace 3 classes from java.beans with its own implementation
  * PropertyChangeEvent
  * PropertyChangeListener
  * PropertyChangeSupport
  * adapted org.jupnp, org.jupnp.osgi, tests to use these implementations instead of java.beans
  * I have to export these compat classes to org.jupnp.osgi bundle too
* Removed the class org.jupnp.util.Gfx
  * is using java.beans, java.awt, javax.swing
  * will NEVER be used in jUPnP internally
* Removed the class org.jupnp.util.Threads
  * is using java.lang.management (JMX)
  * will NEVER be used in jUPnP internally
